# Generated by Django 2.2.10 on 2020-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.CharField(max_length=300, verbose_name='Ссылка на изображение')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('release_date', models.DateField(verbose_name='Дата публикации')),
                ('lte_exists', models.BooleanField(verbose_name='LTE')),
                ('slug', models.SlugField(verbose_name='ЧПУ')),
            ],
        ),
    ]
